version: '2.1'

services:
  ghost:
    image: ghost:latest
    volumes:
      - ./content:/var/lib/ghost
    ports:
      - 2368:2368
    user: ${USERMAP}

  buster:
    image: stefanscherer/buster
    command: /buster.sh
    volumes:
      - ./static:/static
      - ./buster.sh:/buster.sh

  preview:
    image: nginx
    volumes:
      - ./static:/usr/share/nginx/html:ro
    ports:
      - 2369:80
